restart_file: .na
start_datetime: 2022-07-01 00:00:00
end_datetime: .na
forecast_start_datetime: 2022-07-05 00:00:00
forecast_horizon: 2.0
sim_name: feea_test
configure_flare: configure_flare_feea.yml
configure_obs: observation_processing_feea.yml
use_s3: false
