on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    container:
      image: rqthomas/flare-rocker:4.2.1
      #options: -v /c/Users/DKITStaff/Run_Flare_Feeah:/home/rstudio
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
# Point to the right path, run the right Rscript command
      - name: Run automatic prediction file
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run:  Rscript $GITHUB_WORKSPACE/workflows/default/forecast_workflow.R
