on:
  workflow_dispatch:
  #schedule:
  #- cron: "0 11 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    container:
      image: rqthomas/flare-rocker:4.3.2
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
# Point to the right path, run the right Rscript command
      - name: Run automatic prediction file
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run:  Rscript $GITHUB_WORKSPACE/workflows/default/forecast_workflow.R

      - name: Healthcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -m 10 --retry 5 https://hc-ping.com/3c3755e3-a580-424d-8973-3b30ce4d64ff
